name: "Chromatic"
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: npm install
    - uses: chromaui/action@v1
      with:
        appCode: jop5qodv3vl
        token: ${{ secrets.GITHUB_TOKEN }}
        buildScriptName: storybook:build

